# GENERATED by gen-wake-timers.js — do not hand-edit; rerun the generator.
$ErrorActionPreference = 'Continue'
# Best effort: enable wake timers on battery too (AC already Enabled; may need admin)
powercfg /setdcvalueindex SCHEME_CURRENT SUB_SLEEP RTCWAKE 1
powercfg /setactive SCHEME_CURRENT
# Replace any previous set atomically
Get-ScheduledTask -TaskPath '\MarketRadar\' -ErrorAction SilentlyContinue | Unregister-ScheduledTask -Confirm:$false
$action = New-ScheduledTaskAction -Execute 'cmd.exe' -Argument '/c exit'
$settings = New-ScheduledTaskSettingsSet -WakeToRun -StartWhenAvailable -ExecutionTimeLimit (New-TimeSpan -Minutes 5)
$wakes = @(
  @('pce-2026-08-t24h', '2026-08-27T12:15:00Z'),
  @('pce-2026-08-t5m', '2026-08-28T12:20:00Z'),
  @('nfp-2026-09-t24h', '2026-09-03T12:15:00Z'),
  @('nfp-2026-09-t5m', '2026-09-04T12:20:00Z'),
  @('ppi-2026-09-t24h', '2026-09-09T12:15:00Z'),
  @('ppi-2026-09-t5m', '2026-09-10T12:20:00Z'),
  @('cpi-2026-09-t24h', '2026-09-09T12:15:00Z'),
  @('cpi-2026-09-t60m', '2026-09-10T11:15:00Z'),
  @('cpi-2026-09-t5m', '2026-09-10T12:20:00Z'),
  @('cpi-2026-09-t30m', '2026-09-10T12:45:00Z'),
  @('fomc-2026-09-t24h', '2026-09-15T17:45:00Z'),
  @('fomc-2026-09-t60m', '2026-09-16T16:45:00Z'),
  @('fomc-2026-09-t5m', '2026-09-16T17:50:00Z'),
  @('fomc-2026-09-t30m', '2026-09-16T18:15:00Z'),
  @('pce-2026-09-t24h', '2026-09-24T12:15:00Z'),
  @('pce-2026-09-t5m', '2026-09-25T12:20:00Z'),
  @('nfp-2026-10-t24h', '2026-10-01T12:15:00Z'),
  @('nfp-2026-10-t5m', '2026-10-02T12:20:00Z'),
  @('cpi-2026-10-t24h', '2026-10-12T12:15:00Z'),
  @('cpi-2026-10-t60m', '2026-10-13T11:15:00Z'),
  @('cpi-2026-10-t5m', '2026-10-13T12:20:00Z'),
  @('cpi-2026-10-t30m', '2026-10-13T12:45:00Z'),
  @('ppi-2026-10-t24h', '2026-10-14T12:15:00Z'),
  @('ppi-2026-10-t5m', '2026-10-15T12:20:00Z'),
  @('fomc-2026-10-t24h', '2026-10-27T17:45:00Z'),
  @('fomc-2026-10-t60m', '2026-10-28T16:45:00Z'),
  @('fomc-2026-10-t5m', '2026-10-28T17:50:00Z'),
  @('fomc-2026-10-t30m', '2026-10-28T18:15:00Z'),
  @('pce-2026-10-t24h', '2026-10-29T12:15:00Z'),
  @('pce-2026-10-t5m', '2026-10-30T12:20:00Z'),
  @('nfp-2026-11-t24h', '2026-11-05T13:15:00Z'),
  @('nfp-2026-11-t5m', '2026-11-06T13:20:00Z'),
  @('cpi-2026-11-t24h', '2026-11-11T13:15:00Z'),
  @('cpi-2026-11-t60m', '2026-11-12T12:15:00Z'),
  @('cpi-2026-11-t5m', '2026-11-12T13:20:00Z'),
  @('cpi-2026-11-t30m', '2026-11-12T13:45:00Z'),
  @('ppi-2026-11-t24h', '2026-11-12T13:15:00Z'),
  @('ppi-2026-11-t5m', '2026-11-13T13:20:00Z'),
  @('pce-2026-11-t24h', '2026-11-24T13:15:00Z'),
  @('pce-2026-11-t5m', '2026-11-25T13:20:00Z'),
  @('nfp-2026-12-t24h', '2026-12-03T13:15:00Z'),
  @('nfp-2026-12-t5m', '2026-12-04T13:20:00Z'),
  @('fomc-2026-12-t24h', '2026-12-08T18:45:00Z'),
  @('fomc-2026-12-t60m', '2026-12-09T17:45:00Z'),
  @('fomc-2026-12-t5m', '2026-12-09T18:50:00Z'),
  @('fomc-2026-12-t30m', '2026-12-09T19:15:00Z'),
  @('cpi-2026-12-t24h', '2026-12-09T13:15:00Z'),
  @('cpi-2026-12-t60m', '2026-12-10T12:15:00Z'),
  @('cpi-2026-12-t5m', '2026-12-10T13:20:00Z'),
  @('cpi-2026-12-t30m', '2026-12-10T13:45:00Z'),
  @('ppi-2026-12-t24h', '2026-12-14T13:15:00Z'),
  @('ppi-2026-12-t5m', '2026-12-15T13:20:00Z'),
  @('pce-2026-12-t24h', '2026-12-22T13:15:00Z'),
  @('pce-2026-12-t5m', '2026-12-23T13:20:00Z')
)
foreach ($w in $wakes) {
  $local = ([datetime]::Parse($w[1], $null, [System.Globalization.DateTimeStyles]::AdjustToUniversal)).ToLocalTime()
  $trigger = New-ScheduledTaskTrigger -Once -At $local
  Register-ScheduledTask -TaskName ('Wake-' + $w[0]) -TaskPath '\MarketRadar\' -Action $action -Trigger $trigger -Settings $settings -Force | Out-Null
  Write-Output ('created Wake-' + $w[0] + '  utc=' + $w[1] + '  local=' + $local.ToString('yyyy-MM-dd HH:mm'))
}
Write-Output ('TOTAL: ' + (Get-ScheduledTask -TaskPath '\MarketRadar\').Count + ' wake timers registered')
